# Put this file at servermods/serverpacklocator.toml
[client]
# The URL of the minecraft server you wish to fetch mods from.
remoteServer = "https://subdomain.example.com/"
# The server password. This isn't actually used
password = "a"
